name: Find tabs in code and push reports

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ matrix.check-files }}
    steps:
#    - id: set-matrix
      - run: git diff --name-only HEAD
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
        od -c ${{ matrix.check-files }} | grep -o "\t" | wc -l > ${{ matrix.check-files }}.log
        ls -lah
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.check-files }}.log
